<?php

return [
    'social_data' => [
        'tiktok' => [
            'show' => true,
            'thumb' => '/static/imgs/tiktok.png',
            'name' => 'TikTok',
            'uri' => 'https://www.tiktok.com/@',
            'appType' => 'social',
            'appTypeName' => 'Liên kết',
            'showType' => 'iconDirect',
        ],
        'badoo' => [
            'show' => true,
            'thumb' => '/static/imgs/badoo.png',
            'name' => 'Badoo',
            'uri' => '',
            'appType' => 'social',
            'appTypeName' => 'Liên kết',
            'showType' => 'iconDirect',
        ],
        'lazada' => [
            'show' => true,
            'thumb' => '/static/imgs/lazada.jpg',
            'name' => 'Lazada',
            'uri' => '',
            'appType' => 'social',
            'appTypeName' => 'Liên kết',
            'showType' => 'iconDirect',
        ],
        'shopee' => [
            'show' => true,
            'thumb' => '/static/imgs/shopee.png',
            'name' => 'Shopee',
            'uri' => 'https://shopee.vn/',
            'appType' => 'social',
            'appTypeName' => 'Liên kết',
            'showType' => 'iconDirect',
        ],
        'snapchat' => [
            'show' => true,
            'thumb' => '/static/imgs/snapchat.png',
            'name' => 'Snapchat',
            'uri' => 'https://www.snapchat.com/add/',
            'appType' => 'social',
            'appTypeName' => 'Liên kết',
            'showType' => 'iconDirect',
        ],
        'soundcloud' => [
            'show' => true,
            'thumb' => '/static/imgs/soundcloud.jpg',
            'name' => 'Soundcloud',
            'uri' => 'https://soundcloud.com/',
            'appType' => 'social',
            'appTypeName' => 'Liên kết',
            'showType' => 'iconDirect',
        ],
        'spotify' => [
            'show' => true,
            'thumb' => '/static/imgs/spotify.png',
            'name' => 'Spotify',
            'uri' => 'https://open.spotify.com/artist/',
            'appType' => 'social',
            'appTypeName' => 'Liên kết',
            'showType' => 'iconDirect',
        ],
        'website' => [
            'show' => true,
            'thumb' => '/static/imgs/website.png',
            'name' => 'Website',
            'uri' => '',
            'appType' => 'social',
            'appTypeName' => 'Liên kết',
            'showType' => 'iconDirect',
        ],
        'tinder' => [
            'show' => true,
            'thumb' => '/static/imgs/tinder.png',
            'name' => 'Tinder',
            'uri' => 'https://tinder.com/@',
            'appType' => 'social',
            'appTypeName' => 'Liên kết',
            'showType' => 'iconDirect',
        ],
        'pinterest' => [
            'show' => true,
            'thumb' => '/static/imgs/pinterest.png',
            'name' => 'Pinterest',
            'uri' => '',
            'appType' => 'social',
            'appTypeName' => 'Liên kết',
            'showType' => 'iconDirect',
        ],
        'momo' => [
            'show' => true,
            'thumb' => '/static/imgs/momo.png',
            'name' => 'Momo',
            'uri' => '',
            'appType' => 'social',
            'appTypeName' => 'Liên kết',
            'showType' => 'card',
        ],
        'zalo' => [
            'show' => true,
            'thumb' => '/static/imgs/zalo.png',
            'name' => 'Zalo',
            'uri' => '',
            'appType' => 'social',
            'appTypeName' => 'Liên kết',
            'showType' => 'card',
        ],
        
        'facebook' => [
            'show' => true,
            'thumb' => '/static/imgs/facebook.png',
            'name' => 'Facebook',
            'uri' => 'https://www.facebook.com/',
            'appType' => 'social',
            'appTypeName' => 'Liên kết',
            'showType' => 'iconDirect',
        ],
        'instargram' => [
            'show' => true,
            'thumb' => '/static/imgs/instargram.png',
            'name' => 'Instargram',
            'uri' => 'https://www.instagram.com/',
            'appType' => 'social',
            'appTypeName' => 'Liên kết',
            'showType' => 'iconDirect',
        ],
        'youtube' => [
            'show' => true,
            'thumb' => '/static/imgs/youtube.png',
            'name' => 'Youtube',
            'uri' => 'https://www.youtube.com/c/',
            'appType' => 'social',
            'appTypeName' => 'Liên kết',
            'showType' => 'iconDirect',
        ],
        'gmail' => [
            'show' => false,
            'thumb' => '/static/imgs/gmail.jpg',
            'name' => 'Gmail',
            'uri' => '',
            'appType' => 'social',
            'appTypeName' => 'Liên kết',
            'showType' => 'iconDirect',
        ],
        'twitter' => [
            'show' => true,
            'thumb' => '/static/imgs/twitter.png',
            'name' => 'Twitter',
            'uri' => 'https://twitter.com/',
            'appType' => 'social',
            'appTypeName' => 'Liên kết',
            'showType' => 'iconDirect',
        ],
        // 'linkedin' => [
        //     'show' => true,
        //     'thumb' => 'https://cdn1.iconfinder.com/data/icons/logotypes/32/square-linkedin-128.png',
        //     'name' => 'Linkedin',
        //     'uri' => '',
        //     'appType' => 'social',
        //     'appTypeName' => 'Liên kết',
        //     'showType' => 'iconDirect',
        // ],
        

        'agribank' => [
            'show' => true,
            'thumb' => '/static/imgs/bank/agribank.png',
            'name' => 'Agribank',
            'uri' => '',
            'appType' => 'bank',
            'appTypeName' => 'Ngân hàng',
            'showType' => 'card',
        ],
        'mbbank' => [
            'show' => true,
            'thumb' => '/static/imgs/bank/mbbank.png',
            'name' => 'MB Bank',
            'uri' => '',
            'appType' => 'bank',
            'appTypeName' => 'Ngân hàng',
            'showType' => 'card',
        ],
        'sacombank' => [
            'show' => true,
            'thumb' => '/static/imgs/bank/sacombank.png',
            'name' => 'Sacombank',
            'uri' => '',
            'appType' => 'bank',
            'appTypeName' => 'Ngân hàng',
            'showType' => 'card',
        ],
        'shbbank' => [
            'show' => true,
            'thumb' => '/static/imgs/bank/shbbank.png',
            'name' => 'SHB Bank',
            'uri' => '',
            'appType' => 'bank',
            'appTypeName' => 'Ngân hàng',
            'showType' => 'card',
        ],
        'techcombank' => [
            'show' => true,
            'thumb' => '/static/imgs/bank/techcombank.png',
            'name' => 'Techcombank',
            'uri' => '',
            'appType' => 'bank',
            'appTypeName' => 'Ngân hàng',
            'showType' => 'card',
        ],
        'tpbank' => [
            'show' => true,
            'thumb' => '/static/imgs/bank/tpbank.png',
            'name' => 'TP Bank',
            'uri' => '',
            'appType' => 'bank',
            'appTypeName' => 'Ngân hàng',
            'showType' => 'card',
        ],
        'vibbank' => [
            'show' => true,
            'thumb' => '/static/imgs/bank/vibbank.png',
            'name' => 'VIB Bank',
            'uri' => '',
            'appType' => 'bank',
            'appTypeName' => 'Ngân hàng',
            'showType' => 'card',
        ],
        'viettinbank' => [
            'show' => true,
            'thumb' => '/static/imgs/bank/viettinbank.png',
            'name' => 'Viettinbank',
            'uri' => '',
            'appType' => 'bank',
            'appTypeName' => 'Ngân hàng',
            'showType' => 'card',
        ],
        'vpbank' => [
            'show' => true,
            'thumb' => '/static/imgs/bank/vpbank.png',
            'name' => 'VP Bank',
            'uri' => '',
            'appType' => 'bank',
            'appTypeName' => 'Ngân hàng',
            'showType' => 'card',
        ],


        // 'skype' => [
        //     'show' => true,
        //     'thumb' => 'https://cdn2.iconfinder.com/data/icons/social-icons-33/128/Skype-128.png',
        //     'name' => 'Skype',
        //     'uri' => '',
        // 'appType' => 'social',
        // 'appTypeName' => 'Liên kết',
        // 'showType' => 'iconDirect',
        // ],
    ]
];