<?php

return [
    'social_data' => [
        'tiktok' => [
            'show' => true,
            'thumb' => '/static/icons/%s/tiktok.png',
            'name' => 'TikTok',
            'uri' => 'https://www.tiktok.com/@',
            'appType' => 'social',
            'appTypeName' => 'Liên kết',
            'showType' => 'iconDirect',
        ],
        // 'badoo' => [
        //     'show' => true,
        //     'thumb' => '/static/imgs/badoo.png',
        //     'name' => 'Badoo',
        //     'uri' => '',
        //     'appType' => 'social',
        //     'appTypeName' => 'Liên kết',
        //     'showType' => 'iconDirect',
        // ],
        'lazada' => [
            'show' => true,
            'thumb' => '/static/icons/%s/lazada.png',
            'name' => 'Lazada',
            'uri' => '',
            'appType' => 'social',
            'appTypeName' => 'Liên kết',
            'showType' => 'iconDirect',
        ],
        'shopee' => [
            'show' => true,
            'thumb' => '/static/icons/%s/shopee.png',
            'name' => 'Shopee',
            'uri' => 'https://shopee.vn/',
            'appType' => 'social',
            'appTypeName' => 'Liên kết',
            'showType' => 'iconDirect',
        ],
        'snapchat' => [
            'show' => true,
            'thumb' => '/static/icons/%s/snapchat.png',
            'name' => 'Snapchat',
            'uri' => 'https://www.snapchat.com/add/',
            'appType' => 'social',
            'appTypeName' => 'Liên kết',
            'showType' => 'iconDirect',
        ],
        'soundcloud' => [
            'show' => true,
            'thumb' => '/static/icons/%s/soundcloud.png',
            'name' => 'Soundcloud',
            'uri' => 'https://soundcloud.com/',
            'appType' => 'social',
            'appTypeName' => 'Liên kết',
            'showType' => 'iconDirect',
        ],
        'spotify' => [
            'show' => true,
            'thumb' => '/static/icons/%s/spotify.png',
            'name' => 'Spotify',
            'uri' => 'https://open.spotify.com/artist/',
            'appType' => 'social',
            'appTypeName' => 'Liên kết',
            'showType' => 'iconDirect',
        ],
        'website' => [
            'show' => true,
            'thumb' => '/static/icons/%s/url.png',
            'name' => 'Website',
            'uri' => '',
            'appType' => 'social',
            'appTypeName' => 'Liên kết',
            'showType' => 'iconDirect',
        ],
        'wechat' => [
            'show' => true,
            'thumb' => '/static/icons/%s/wechat.png',
            'name' => 'Wechat',
            'uri' => '',
            'appType' => 'social',
            'appTypeName' => 'Liên kết',
            'showType' => 'iconDirect',
        ],
        'whatsapp' => [
            'show' => true,
            'thumb' => '/static/icons/%s/whatsapp.png',
            'name' => 'Whatsapp',
            'uri' => '',
            'appType' => 'social',
            'appTypeName' => 'Liên kết',
            'showType' => 'iconDirect',
        ],
        // 'tinder' => [
        //     'show' => true,
        //     'thumb' => '/static/imgs/tinder.png',
        //     'name' => 'Tinder',
        //     'uri' => 'https://tinder.com/@',
        //     'appType' => 'social',
        //     'appTypeName' => 'Liên kết',
        //     'showType' => 'iconDirect',
        // ],
        'pinterest' => [
            'show' => true,
            'thumb' => '/static/icons/%s/pinterest.png',
            'name' => 'Pinterest',
            'uri' => '',
            'appType' => 'social',
            'appTypeName' => 'Liên kết',
            'showType' => 'iconDirect',
        ],
        'momo' => [
            'show' => true,
            'thumb' => '/static/icons/%s/momo.png',
            'name' => 'Momo',
            'uri' => 'https://nhantien.momo.vn/',
            'appType' => 'social',
            'appTypeName' => 'Liên kết',
            'showType' => 'iconDirect',
        ],
        'zalo' => [
            'show' => true,
            'thumb' => '/static/icons/%s/zalo.png',
            'name' => 'Zalo',
            'uri' => 'https://zalo.me/',
            'appType' => 'social',
            'appTypeName' => 'Liên kết',
            'showType' => 'iconDirect',
        ],
        
        'facebook' => [
            'show' => true,
            'thumb' => '/static/icons/%s/facebook.png',
            'name' => 'Facebook',
            'uri' => 'https://www.facebook.com/',
            'appType' => 'social',
            'appTypeName' => 'Liên kết',
            'showType' => 'iconDirect',
        ],
        'telegram' => [
            'show' => true,
            'thumb' => '/static/icons/%s/telegram.png',
            'name' => 'Facebook',
            'uri' => '',
            'appType' => 'social',
            'appTypeName' => 'Liên kết',
            'showType' => 'iconDirect',
        ],
        'instargram' => [
            'show' => true,
            'thumb' => '/static/icons/%s/instagram.png',
            'name' => 'Instargram',
            'uri' => 'https://www.instagram.com/',
            'appType' => 'social',
            'appTypeName' => 'Liên kết',
            'showType' => 'iconDirect',
        ],
        'youtube' => [
            'show' => true,
            'thumb' => '/static/icons/%s/youtube.png',
            'name' => 'Youtube',
            'uri' => 'https://www.youtube.com/c/',
            'appType' => 'social',
            'appTypeName' => 'Liên kết',
            'showType' => 'iconDirect',
        ],
        // 'gmail' => [
        //     'show' => false,
        //     'thumb' => '/static/imgs/gmail.jpg',
        //     'name' => 'Gmail',
        //     'uri' => '',
        //     'appType' => 'social',
        //     'appTypeName' => 'Liên kết',
        //     'showType' => 'iconDirect',
        // ],
        'twitter' => [
            'show' => true,
            'thumb' => '/static/icons/%s/twitter.png',
            'name' => 'Twitter',
            'uri' => 'https://twitter.com/',
            'appType' => 'social',
            'appTypeName' => 'Liên kết',
            'showType' => 'iconDirect',
        ],
        'line' => [
            'show' => true,
            'thumb' => '/static/icons/%s/line.png',
            'name' => 'Line',
            'uri' => '',
            'appType' => 'social',
            'appTypeName' => 'Liên kết',
            'showType' => 'iconDirect',
        ],
        'linkedin' => [
            'show' => true,
            'thumb' => '/static/icons/%s/linkedin.png',
            'name' => 'Linkedin',
            'uri' => '',
            'appType' => 'social',
            'appTypeName' => 'Liên kết',
            'showType' => 'iconDirect',
        ],
        'agribank' => [
            'show' => true,
            'thumb' => '/static/icons/%s/agribank.png',
            'name' => 'Agribank',
            'uri' => '',
            'appType' => 'bank',
            'appTypeName' => 'Ngân hàng',
            'showType' => 'card',
        ],
        'mbbank' => [
            'show' => true,
            'thumb' => '/static/icons/%s/mb.png',
            'name' => 'MB Bank',
            'uri' => '',
            'appType' => 'bank',
            'appTypeName' => 'Ngân hàng',
            'showType' => 'card',
        ],
        // 'sacombank' => [
        //     'show' => true,
        //     'thumb' => '/static/imgs/bank/saacbcombank.png',
        //     'name' => 'Sacombank',
        //     'uri' => '',
        //     'appType' => 'bank',
        //     'appTypeName' => 'Ngân hàng',
        //     'showType' => 'card',
        // ],
        'msb' => [
            'show' => true,
            'thumb' => '/static/icons/%s/msb.png',
            'name' => 'Maritime Bank',
            'uri' => '',
            'appType' => 'bank',
            'appTypeName' => 'Ngân hàng',
            'showType' => 'card',
        ],
        'techcombank' => [
            'show' => true,
            'thumb' => '/static/icons/%s/tcb.png',
            'name' => 'Techcombank',
            'uri' => '',
            'appType' => 'bank',
            'appTypeName' => 'Ngân hàng',
            'showType' => 'card',
        ],
        'acb' => [
            'show' => true,
            'thumb' => '/static/icons/%s/acb.png',
            'name' => 'ACB',
            'uri' => '',
            'appType' => 'bank',
            'appTypeName' => 'Ngân hàng',
            'showType' => 'card',
        ],
        'tpbank' => [
            'show' => true,
            'thumb' => '/static/icons/%s/tpb.png',
            'name' => 'TP Bank',
            'uri' => '',
            'appType' => 'bank',
            'appTypeName' => 'Ngân hàng',
            'showType' => 'card',
        ],
        'vibbank' => [
            'show' => true,
            'thumb' => '/static/icons/%s/vib.png',
            'name' => 'VIB Bank',
            'uri' => '',
            'appType' => 'bank',
            'appTypeName' => 'Ngân hàng',
            'showType' => 'card',
        ],
        'viettinbank' => [
            'show' => true,
            'thumb' => '/static/icons/%s/vtb.png',
            'name' => 'Viettinbank',
            'uri' => '',
            'appType' => 'bank',
            'appTypeName' => 'Ngân hàng',
            'showType' => 'card',
        ],
        'bidv' => [
            'show' => true,
            'thumb' => '/static/icons/%s/bidv.png',
            'name' => 'BIDV',
            'uri' => '',
            'appType' => 'bank',
            'appTypeName' => 'Ngân hàng',
            'showType' => 'card',
        ],
        'vietcombank' => [
            'show' => true,
            'thumb' => '/static/icons/%s/vcb.png',
            'name' => 'Vietcombank',
            'uri' => '',
            'appType' => 'bank',
            'appTypeName' => 'Ngân hàng',
            'showType' => 'card',
        ],
        'vpbank' => [
            'show' => true,
            'thumb' => '/static/icons/%s/vpb.png',
            'name' => 'VP Bank',
            'uri' => '',
            'appType' => 'bank',
            'appTypeName' => 'Ngân hàng',
            'showType' => 'card',
        ],
        'skype' => [
            'show' => true,
            'thumb' => '/static/icons/%s/skype.png',
            'name' => 'Skype',
            'uri' => '',
            'appType' => 'social',
            'appTypeName' => 'Liên kết',
            'showType' => 'iconDirect',
        ],
    ]
];